"""Auto-generate git branches and PRs for evolved skills.

Creates a branch in the hermes-agent repository, copies the evolved
skill, commits with structured metadata, and creates a PR via gh CLI.

Usage (called from evolve_skill.py):
    create_evolution_branch(skill_name, evolved_path, baseline_path, metrics, hermes_repo)
"""

import json
import subprocess
import sys
from datetime import datetime
from pathlib import Path
from typing import Optional


def _run_git(cmd: list[str], cwd: Path) -> subprocess.CompletedProcess:
    """Run a git command and return the result."""
    return subprocess.run(
        ["git"] + cmd,
        capture_output=True, text=True,
        cwd=str(cwd),
        timeout=60,
    )


def _check_repo_clean(hermes_repo: Path) -> bool:
    """Check if the hermes-agent repo has no uncommitted changes."""
    if not hermes_repo.exists():
        return False
    result = _run_git(["status", "--porcelain"], hermes_repo)
    return len(result.stdout.strip()) == 0


def _branch_name(skill_name: str) -> str:
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    safe_name = skill_name.replace("_", "-").replace(" ", "-")
    return f"evolve/{safe_name}-{ts}"


def _commit_message(skill_name: str, metrics: dict) -> str:
    """Build a structured commit message with evolution metadata."""
    baseline = metrics.get("baseline_score", "?")
    evolved = metrics.get("evolved_score", "?")
    improvement = metrics.get("improvement", 0)
    iterations = metrics.get("iterations", "?")
    dataset_source = metrics.get("eval_source", "synthetic")
    n_train = metrics.get("train_examples", "?")
    constraints = "passed" if metrics.get("constraints_passed") else "failed"

    lines = [
        f"evolve: {skill_name} — {baseline} → {evolved} ({improvement:+.3f})",
        "",
        f"Optimizer: GEPA ({iterations} iterations)",
        f"Eval dataset: {dataset_source} ({n_train} training examples)",
        f"Baseline score: {baseline}",
        f"Evolved score: {evolved}",
        f"Improvement: {improvement:+.3f}",
        f"Constraints: {constraints}",
        "",
        "Co-Authored-By: Hermes Agent Self-Evolution <evolution@hermes.ai>",
    ]
    return "\n".join(lines)


def _pr_body(skill_name: str, metrics: dict) -> str:
    """Build a PR body with full comparison."""
    baseline = metrics.get("baseline_score", "?")
    evolved = metrics.get("evolved_score", "?")
    improvement = metrics.get("improvement", 0)
    imp_pct = improvement / max(0.001, baseline) * 100 if baseline != "?" else 0
    iterations = metrics.get("iterations", "?")
    n_train = metrics.get("train_examples", "?")
    n_holdout = metrics.get("holdout_examples", "?")
    elapsed = metrics.get("elapsed_seconds", "?")

    lines = [
        f"## Evolution Result: {skill_name}",
        "",
        f"**Score:** {baseline} → {evolved} **({imp_pct:+.1f}%)**",
        "",
        "### Metrics",
        "",
        f"| Metric | Value |",
        "|--------|-------|",
        f"| Baseline Score | {baseline} |",
        f"| Evolved Score | {evolved} |",
        f"| Improvement | {improvement:+.3f} |",
        f"| Iterations | {iterations} |",
        f"| Training Examples | {n_train} |",
        f"| Holdout Examples | {n_holdout} |",
        f"| Optimization Time | {elapsed}s |",
        "",
        "### Constraint Validation",
        "",
        f"**Result:** {'✅ All passed' if metrics.get('constraints_passed') else '❌ Some failed'}",
        "",
        "### Review Notes",
        "",
        "- Review the diff carefully before merging.",
        "- Run TBLite or full benchmark suite to check for regressions.",
        "- If the improvement is marginal (<1%), consider if the change is worth deploying.",
        "",
        "---",
        "*Generated by Hermes Agent Self-Evolution*",
    ]
    return "\n".join(lines)


def create_evolution_branch(
    skill_name: str,
    evolved_skill_path: Path,
    baseline_skill_path: Path,
    metrics_path: Path,
    hermes_repo: Path,
    dry_run: bool = False,
) -> Optional[str]:
    """Create a git branch + commit in the hermes-agent repo.

    Args:
        skill_name: Name of evolved skill.
        evolved_skill_path: Path to the evolved SKILL.md.
        baseline_skill_path: Path to the baseline SKILL.md.
        metrics_path: Path to the metrics JSON.
        hermes_repo: Path to hermes-agent git repo.
        dry_run: If True, print what would be done without doing it.

    Returns:
        Branch name if successful, None otherwise.
    """
    if not hermes_repo.exists():
        print(f"Error: hermes-agent repo not found at {hermes_repo}", file=sys.stderr)
        return None

    if not _check_repo_clean(hermes_repo):
        print("Error: hermes-agent repo has uncommitted changes. Commit or stash first.", file=sys.stderr)
        return None

    if not evolved_skill_path.exists():
        print(f"Error: evolved skill not found at {evolved_skill_path}", file=sys.stderr)
        return None

    with open(metrics_path) as f:
        metrics = json.load(f)

    branch = _branch_name(skill_name)

    if dry_run:
        print(f"[DRY RUN] Would create branch: {branch}")
        print(f"[DRY RUN] Would copy {evolved_skill_path} to hermes-agent skills/{skill_name}/SKILL.md")
        print(f"[DRY RUN] Would commit with message:\n{_commit_message(skill_name, metrics)}")
        print(f"[DRY RUN] Would create PR with body:\n{_pr_body(skill_name, metrics)}")
        return branch

    # 1. Create branch
    result = _run_git(["checkout", "-b", branch], hermes_repo)
    if result.returncode != 0:
        print(f"Error creating branch: {result.stderr.strip()}", file=sys.stderr)
        return None

    # 2. Find the skill directory in hermes-agent
    skills_base = hermes_repo / "skills"
    skill_dir_candidates = list(skills_base.rglob(f"{skill_name}/SKILL.md"))
    if not skill_dir_candidates:
        print(f"Error: skill directory not found for '{skill_name}' in {skills_base}", file=sys.stderr)
        _run_git(["checkout", "-"], hermes_repo)  # undo branch
        return None
    target_skill_path = skill_dir_candidates[0]

    # 3. Copy evolved skill
    target_skill_path.write_text(evolved_skill_path.read_text(encoding="utf-8"), encoding="utf-8")

    # 4. Stage and commit
    _run_git(["add", str(target_skill_path)], hermes_repo)
    commit_msg = _commit_message(skill_name, metrics)
    result = _run_git(["commit", "-m", commit_msg], hermes_repo)
    if result.returncode != 0:
        print(f"Error committing: {result.stderr.strip()}", file=sys.stderr)
        _run_git(["checkout", "-"], hermes_repo)
        return None

    # 5. Push
    result = _run_git(["push", "origin", branch], hermes_repo)
    if result.returncode != 0:
        print(f"Warning: push failed (remote may not be configured): {result.stderr.strip()}", file=sys.stderr)

    # 6. Create PR
    pr_body_text = _pr_body(skill_name, metrics)
    title = f"evolve: {skill_name} — {metrics.get('baseline_score', '?')} → {metrics.get('evolved_score', '?')}"
    pr_result = subprocess.run(
        ["gh", "pr", "create", "--title", title, "--body", pr_body_text],
        capture_output=True, text=True,
        cwd=str(hermes_repo),
        timeout=120,
    )
    if pr_result.returncode == 0:
        print(f"PR created: {pr_result.stdout.strip()}")
    else:
        print(f"Warning: PR creation failed (is gh authenticated?): {pr_result.stderr.strip()}", file=sys.stderr)

    return branch
