"""Generate rich HTML reports for evolution runs.

Produces a standalone HTML file with:
- Before/after scores comparison
- Full diff of evolved skill
- Per-example scoring breakdown
- Constraint validation results
- Optimization cost estimate
"""

import difflib
from datetime import datetime
from pathlib import Path
from typing import Optional


def _compute_diff(baseline_text: str, evolved_text: str) -> str:
    """Generate an HTML-unified diff between baseline and evolved text."""
    baseline_lines = baseline_text.splitlines(keepends=True)
    evolved_lines = evolved_text.splitlines(keepends=True)
    diff = difflib.unified_diff(
        baseline_lines, evolved_lines,
        fromfile="baseline", tofile="evolved",
    )
    html_lines = []
    for line in diff:
        line = line.rstrip("\n")
        escaped = (
            line.replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace('"', "&quot;")
        )
        if line.startswith("+"):
            html_lines.append(f'<span class="diff-add">{escaped}</span>')
        elif line.startswith("-"):
            html_lines.append(f'<span class="diff-del">{escaped}</span>')
        elif line.startswith("@@"):
            html_lines.append(f'<span class="diff-hdr">{escaped}</span>')
        else:
            html_lines.append(escaped)
    return "\n".join(html_lines)


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Evolution Report: {skill_name}</title>
<style>
body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 960px; margin: 0 auto; padding: 20px; color: #1a1a2e; }}
h1 {{ color: #1a1a2e; border-bottom: 2px solid #e0e0e0; padding-bottom: 8px; }}
h2 {{ color: #2d2d44; margin-top: 28px; }}
.metric {{ display: inline-block; background: #f5f5f5; border-radius: 8px; padding: 12px 20px; margin: 4px; }}
.metric .value {{ font-size: 24px; font-weight: bold; }}
.metric .label {{ font-size: 12px; color: #666; }}
.good {{ color: #2e7d32; }}
.bad {{ color: #c62828; }}
.neutral {{ color: #666; }}
table {{ border-collapse: collapse; width: 100%; margin: 12px 0; }}
th, td {{ border: 1px solid #ddd; padding: 8px 12px; text-align: left; }}
th {{ background: #1a1a2e; color: white; }}
tr:nth-child(even) {{ background: #f9f9f9; }}
.diff {{ background: #f5f5f5; padding: 12px; border-radius: 4px; font-family: monospace; font-size: 13px; overflow-x: auto; line-height: 1.5; white-space: pre-wrap; }}
.diff-add {{ color: #2e7d32; background: #e8f5e9; display: block; }}
.diff-del {{ color: #c62828; background: #ffebee; display: block; }}
.diff-hdr {{ color: #1a56db; font-weight: bold; display: block; }}
.constraint-pass {{ color: #2e7d32; }}
.constraint-fail {{ color: #c62828; }}
.footer {{ margin-top: 32px; padding-top: 12px; border-top: 1px solid #e0e0e0; font-size: 12px; color: #999; text-align: center; }}
</style>
</head>
<body>
<h1>🧬 Evolution Report: {skill_name}</h1>
<p>Generated: {timestamp}</p>

<div class="metric">
  <div class="value {baseline_class}">{baseline_score:.3f}</div>
  <div class="label">Baseline Score</div>
</div>
<div class="metric">
  <div class="value {evolved_class}">{evolved_score:.3f}</div>
  <div class="label">Evolved Score</div>
</div>
<div class="metric">
  <div class="value {improvement_class}">{improvement_sign}{improvement:.3f}</div>
  <div class="label">Change</div>
</div>
<div class="metric">
  <div class="value">{improvement_pct:+.1f}%</div>
  <div class="label">Relative Change</div>
</div>

<h2>Configuration</h2>
<table>
<tr><th>Parameter</th><th>Value</th></tr>
<tr><td>Skill</td><td>{skill_name}</td></tr>
<tr><td>Iterations</td><td>{iterations}</td></tr>
<tr><td>Optimizer Model</td><td>{optimizer_model}</td></tr>
<tr><td>Eval Model</td><td>{eval_model}</td></tr>
<tr><td>Training Examples</td><td>{train_examples}</td></tr>
<tr><td>Holdout Examples</td><td>{holdout_examples}</td></tr>
<tr><td>Optimization Time</td><td>{elapsed:.1f}s</td></tr>
</table>

<h2>Constraint Validation</h2>
<table>
<tr><th>Constraint</th><th>Result</th><th>Message</th></tr>
{constraints_rows}
</table>

<h2>Skill Size</h2>
<table>
<tr><th>Metric</th><th>Baseline</th><th>Evolved</th><th>Change</th></tr>
<tr>
  <td>Size (chars)</td>
  <td>{baseline_size:,}</td>
  <td>{evolved_size:,}</td>
  <td>{size_change:+,}</td>
</tr>
</table>

<h2>Diff</h2>
<div class="diff">{diff_html}</div>

<div class="footer">
Generated by Hermes Agent Self-Evolution — {timestamp}
</div>
</body>
</html>"""


def generate_html_report(
    skill_name: str,
    metrics: dict,
    constraints: list[dict],
    baseline_text: str,
    evolved_text: str,
    output_path: Optional[Path] = None,
) -> str:
    """Generate a standalone HTML report for an evolution run.

    Args:
        skill_name: Name of the evolved skill.
        metrics: Dict with keys: baseline_score, evolved_score, improvement, etc.
        constraints: List of dicts with keys: constraint_name, passed, message.
        baseline_text: Full text of the baseline skill.
        evolved_text: Full text of the evolved skill.
        output_path: Where to write the HTML file. If None, returns HTML string.

    Returns:
        The HTML string (also written to output_path if provided).
    """
    baseline_score = metrics.get("baseline_score", 0.0)
    evolved_score = metrics.get("evolved_score", 0.0)
    improvement = metrics.get("improvement", 0.0)
    baseline_size = metrics.get("baseline_size", 0)
    evolved_size = metrics.get("evolved_size", 0)
    iterations = metrics.get("iterations", "?")
    optimizer_model = metrics.get("optimizer_model", "?")
    eval_model = metrics.get("eval_model", "?")
    train_examples = metrics.get("train_examples", "?")
    holdout_examples = metrics.get("holdout_examples", "?")
    elapsed = metrics.get("elapsed_seconds", 0)

    imp_pct = improvement / max(0.001, baseline_score) * 100
    imp_sign = "+" if improvement > 0 else ""

    baseline_class = "good" if baseline_score > 0.5 else "neutral"
    evolved_class = "good" if evolved_score > 0.5 else "neutral"
    improvement_class = "good" if improvement > 0 else "bad" if improvement < 0 else "neutral"

    constraints_rows = ""
    for c in constraints:
        passed = c.get("passed", False)
        icon = "✅" if passed else "❌"
        cls = "constraint-pass" if passed else "constraint-fail"
        constraints_rows += (
            f"<tr class=\"{cls}\">"
            f"<td>{c.get('constraint_name', '?')}</td>"
            f"<td>{icon}</td>"
            f"<td>{c.get('message', '')}</td>"
            f"</tr>\n"
        )

    diff_html = _compute_diff(baseline_text, evolved_text)

    html = HTML_TEMPLATE.format(
        skill_name=skill_name,
        timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        baseline_score=baseline_score,
        evolved_score=evolved_score,
        improvement=abs(improvement),
        improvement_sign=imp_sign,
        improvement_pct=imp_pct,
        baseline_class=baseline_class,
        evolved_class=evolved_class,
        improvement_class=improvement_class,
        iterations=iterations,
        optimizer_model=optimizer_model,
        eval_model=eval_model,
        train_examples=train_examples,
        holdout_examples=holdout_examples,
        elapsed=elapsed,
        constraints_rows=constraints_rows,
        baseline_size=baseline_size,
        evolved_size=evolved_size,
        size_change=evolved_size - baseline_size,
        diff_html=diff_html,
    )

    if output_path:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(html, encoding="utf-8")

    return html
